#!/usr/bin/env python3
"""Generate the TODD benchmark comparison report from paper data and qsyn results.

Inputs (relative to repo root):
  benchmark/paper-todd.csv  -- hand-transcribed T-counts from the two papers
  qsyn-bench/results.csv    -- output of scripts/todd-benchmark.sh runs

Output:
  qsyn-bench/benchmark-comparison.md  -- grouped comparison table + findings
                                         (review, then copy to docs/ to publish)
"""

import csv
import sys
from datetime import date
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
PAPER_CSV = REPO_ROOT / "benchmark" / "paper-todd.csv"
RESULTS_CSV = REPO_ROOT / "qsyn-bench" / "results.csv"
OUTPUT_MD = REPO_ROOT / "qsyn-bench" / "benchmark-comparison.md"

GROUP_ORDER = ["common", "heyfron-only", "vandaele-only"]
GROUP_TITLES = {
    "common": "Circuits in both papers",
    "heyfron-only": "Heyfron 2018 only",
    "vandaele-only": "Vandaele 2024 only",
}


def load_paper_rows():
    with open(PAPER_CSV, newline="") as f:
        return list(csv.DictReader(f))


def load_results():
    if not RESULTS_CSV.exists():
        return {}
    with open(RESULTS_CSV, newline="") as f:
        return {row["circuit"]: row for row in csv.DictReader(f)}


def fmt(value, suffix=""):
    return f"{value}{suffix}" if value not in ("", None) else "-"


def delta_cell(qsyn_post, paper_todd):
    if not qsyn_post or not paper_todd:
        return "-"
    diff = int(qsyn_post) - int(paper_todd)
    return f"{diff:+d}"


def main():
    paper_rows = load_paper_rows()
    results = load_results()

    lines = [
        "# TODD Benchmark Comparison: qsyn vs. published results",
        "",
        f"*Generated by `just report` on {date.today().isoformat()}.*",
        "",
        "## Methodology",
        "",
        "qsyn implements the base **TODD** algorithm of Heyfron & Campbell 2018",
        "(`src/tableau/optimize/todd.cpp`, CLI `tableau optimize phasepoly todd`).",
        "This report compares the T-counts **published in the papers' benchmark tables** against",
        "a **real run** of qsyn's pipeline on the same standard reversible-logic",
        "circuits (Maslov/Amy benchmark suite, `benchmark/qc/optimized/`).",
        "",
        "- **qsyn run**: `qcir read` -> `convert qcir tableau` -> `tableau optimize full`",
        "  (FastTMerge-style rotation merging + internal-H optimization + TODD, looped",
        "  until the T-count stops decreasing) -> `convert tableau qcir` -> T-count from",
        "  `qcir print --stat`. No ancillae, no Hadamard gadgetization.",
        "- **Heyfron 2018, Table I (TODD column)**: TODD *with* Hadamard gadgetization -",
        "  every internal H becomes an ancilla. More optimization room than qsyn's",
        "  setting, so these numbers are a *lower-is-easier* reference, not",
        "  apples-to-apples.",
        "- **Vandaele 2024, Table 2 (TODD / FastTODD columns)**: no ancillary qubits,",
        "  circuits pre-optimized with FastTMerge then split into Hadamard-free",
        "  subcircuits. This is the setting closest to qsyn's pipeline.",
        "",
        "### Caveats",
        "",
        "- Input files are the **pyzx pre-optimized** versions shipped in this repo,",
        "  while the papers start from raw circuits and apply their own",
        "  pre-optimization. Input T-counts therefore differ (qsyn's `pre T` column",
        "  shows what qsyn actually started from); the comparison metric is the",
        "  **final post-TODD T-count**, which targets the same underlying unitary.",
        "- `T*`/`S*` tokens in the `.qc` files were rewritten to `tdg`/`sdg` for",
        "  qsyn's reader (`just prepare`); this is a pure notation change.",
        "- Heyfron's `NC Toff_k` rows are matched to `tof_*` files by qubit count",
        "  (e.g. NC Toff4 = `tof_3`, n=5).",
        "- `mod5_4` is absent from Vandaele Table 2; its Vandaele numbers come from",
        "  Table 1 (gadgetized) and are marked with *.",
        "",
        "## Results",
        "",
        "T-counts; lower is better. In the `qsyn TODD` column, **bold** = better",
        "and *italic* = worse than the best published TODD value in the same row",
        "(minimum of the Heyfron and Vandaele TODD columns); plain = equal.",
        "`DNF` = qsyn was killed at the",
        "per-circuit timeout without producing a result; the `time (s)` column",
        "shows that cap (e.g. `>1800`). `-` = not available (no published",
        "value / no circuit file / not run).",
        "",
        "The `equiv` column reports whether qsyn proved the optimized circuit "
        "equivalent to the original (`qcir equiv`): `pass` = proven equivalent, "
        "`FAIL` = proven NOT equivalent (correctness bug), `?` = unverified "
        "(too large to check; possible false negative), `-` = check not reached.",
        "",
    ]

    header = (
        "| Circuit | n | Heyfron TODD | Vandaele TODD | Vandaele FastTODD "
        "| qsyn pre | qsyn TODD | time (s) | equiv |"
    )
    separator = "|---|---|---|---|---|---|---|---|---|"

    # Comparison reference: best (minimum) published TODD value in the row,
    # across both papers and regardless of setting.
    summary = {
        "better": [],
        "equal": [],
        "worse": [],
        "dnf": [],
        "missing": [],
        "equiv_fail": [],
        "equiv_unverified": [],
    }

    equiv_cells = {
        "pass": "pass",
        "FAIL": "**FAIL**",
        "unverified": "?",
    }

    for group in GROUP_ORDER:
        rows = sorted(
            (r for r in paper_rows if r["group"] == group),
            key=lambda r: r["circuit"].lower(),
        )
        if not rows:
            continue
        lines += [f"### {GROUP_TITLES[group]}", "", header, separator]
        for row in rows:
            circuit = row["circuit"]
            res = results.get(circuit, {})
            status = res.get("status", "")
            qsyn_pre = res.get("pre_T", "")
            qsyn_post = res.get("post_T", "")
            qsyn_time = res.get("wall_seconds", "")
            equiv = res.get("equiv", "")

            mark = "*" if "Table 1" in row.get("notes", "") else ""
            heyfron = fmt(row["heyfron_todd_T"])
            vandaele = fmt(row["vandaele_todd_T"], mark)
            fasttodd = fmt(row["vandaele_fasttodd_T"], mark)

            paper_ref = min(
                (int(v) for v in (row["heyfron_todd_T"], row["vandaele_todd_T"]) if v),
                default=None,
            )

            equiv_cell = equiv_cells.get(equiv, "-")
            if status == "ok" and qsyn_post:
                post_cell = qsyn_post
                if paper_ref is not None:
                    diff = int(qsyn_post) - paper_ref
                    if diff < 0:
                        post_cell = f"**{qsyn_post}**"
                    elif diff > 0:
                        post_cell = f"*{qsyn_post}*"
                    key = "better" if diff < 0 else "equal" if diff == 0 else "worse"
                    summary[key].append((circuit, int(qsyn_post), paper_ref))
                time_cell = qsyn_time
                if equiv == "FAIL":
                    summary["equiv_fail"].append(circuit)
                elif equiv == "unverified":
                    summary["equiv_unverified"].append(circuit)
            elif status == "DNF":
                post_cell, time_cell = "DNF", f">{qsyn_time}"
                summary["dnf"].append(circuit)
            elif status == "error":
                post_cell, time_cell = "error", "-"
                summary["missing"].append(circuit)
            else:
                post_cell, time_cell = "-", "-"
                summary["missing"].append(circuit)

            lines.append(
                f"| `{circuit}` | {row['n']} | {heyfron} | {vandaele} | {fasttodd} "
                f"| {fmt(qsyn_pre)} | {post_cell} | {time_cell} | {equiv_cell} |"
            )
        lines.append("")

    lines += ["## Findings", ""]
    ran = summary["better"] + summary["equal"] + summary["worse"]
    if ran:
        lines.append(
            f"- Against the best published TODD value per circuit (either paper), "
            f"qsyn completed **{len(ran)}** circuits: better "
            f"on {len(summary['better'])}, equal on {len(summary['equal'])}, "
            f"worse on {len(summary['worse'])}."
        )
        if summary["better"]:
            cells = ", ".join(
                f"`{c}` ({q} vs {p})" for c, q, p in sorted(summary["better"])
            )
            lines.append(f"- Better than the best published TODD on: {cells}.")
        if summary["worse"]:
            cells = ", ".join(
                f"`{c}` ({q} vs {p})" for c, q, p in sorted(summary["worse"])
            )
            lines.append(f"- Worse than the best published TODD on: {cells}.")
    if summary["dnf"]:
        lines.append(
            "- Timed out (DNF): "
            + ", ".join(f"`{c}`" for c in sorted(summary["dnf"]))
            + "."
        )
    if summary["missing"]:
        lines.append(
            "- Not run (no circuit file, read error, or skipped): "
            + ", ".join(f"`{c}`" for c in sorted(summary["missing"]))
            + "."
        )
    if summary["equiv_fail"]:
        lines.append(
            "- **Equivalence FAILED** (optimized circuit proven NOT equal to the "
            "original — a correctness bug, the T-count is meaningless): "
            + ", ".join(f"`{c}`" for c in sorted(summary["equiv_fail"]))
            + "."
        )
    if summary["equiv_unverified"]:
        lines.append(
            "- Equivalence unverified (too large for tensor contraction and not "
            "provable by the tableau method; may be a false negative — treat the "
            "T-count as unconfirmed): "
            + ", ".join(f"`{c}`" for c in sorted(summary["equiv_unverified"]))
            + "."
        )
    lines += [
        "",
        "Where qsyn lags the *gadgetized* Heyfron numbers but matches the",
        "no-ancilla Vandaele numbers, the gap is attributable to Hadamard",
        "gadgetization (which qsyn does not implement), not to the TODD core.",
        "Circuits where qsyn lags the no-ancilla Vandaele TODD column indicate",
        "genuine optimization opportunities for the FastTODD work planned in",
        "`FinalProject.md`.",
        "",
        "## References",
        "",
        "- L. Heyfron, E. T. Campbell, *An Efficient Quantum Compiler that reduces",
        "  T count*, arXiv:1712.01557 (Table I).",
        "- V. Vandaele, *Lower T-count with faster algorithms*, arXiv:2407.08695",
        "  (Tables 1-2).",
        "",
    ]

    OUTPUT_MD.write_text("\n".join(lines))
    print(f"wrote {OUTPUT_MD.relative_to(REPO_ROOT)}")
    if not results:
        print(
            "warning: no results.csv found; table contains paper data only",
            file=sys.stderr,
        )


if __name__ == "__main__":
    main()
